version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - "5000:80"
    volumes:
      - tooling_frontend:/var/www/html
    environment:
      MYSQL_IP: db  # The hostname of your database service
      MYSQL_USER: celyne
      MYSQL_PASS: PassWord.1
      MYSQL_DBNAME: toolingdb
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: celyne
      MYSQL_PASSWORD: PassWord.1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db: